#!/bin/sh
# before git commit, this hook enforces linting with JSHint and Google Closure Linter

jshintresult=$(jshint .)
gjslintresult=$(gjslint -r .)

valid=true

# empty response -> no errors
if [ "$jshintresult" != "" ]; then
  printf "JSHint validation unsuccessful:\n$jshintresult"
  valid=false
else
  printf "JSHint validation successful"
fi

# check if the GCL result contains "Line" (meaning error(s) was found)
if [[ $gjslintresult == *Line* ]]; then
  printf "\n\nClosure Linter validation unsuccessful:\n$gjslintresult"
  valid=false
else
  printf "\nClosure Linter validation successful"
fi

if ! $valid; then
  exit 1
else
  exit 0
fi
