#!/bin/sh
# before git commit, this hook enforces linting with JSHint and Google Closure Linter

jshintresult=$(jshint .)

ignored=""
# get ignored files and comma-separate them
ignored=$(tr '\n' ',' < .jshintignore)

# prepare the GCL command, excluding files if necessary
gclcommand="gjslint -r ."
if [ "$ignored" != "" ]; then
	gclcommand+=" -x $ignored"
fi

gjslintresult=$($gclcommand)

valid=true

# empty response -> no errors
if [ "$jshintresult" != "" ]; then
	printf "JSHint validation unsuccessful:\n$jshintresult\n"
	valid=false
else
	printf "JSHint validation successful\n"
fi

# check if the GCL result contains "Line" (meaning error(s) was found)
if [[ $gjslintresult == *Line* ]]; then
	printf "\n\nClosure Linter validation unsuccessful:\n$gjslintresult\n"
	valid=false
else
	printf "Closure Linter validation successful\n"
fi

if ! $valid; then
	exit 1
else
	exit 0
fi
